# Generated by Django 5.2.3 on 2025-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'In Sospeso'), ('Processing', 'In Lavorazione'), ('Shipped', 'Spedito'), ('Delivered', 'Consegnato'), ('Cancelled', 'Annullato')], default='Pending', max_length=50),
        ),
    ]
