# Generated by Django 5.2.3 on 2025-06-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_phone_number_and_more'),
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
