# Generated by Django 5.2.3 on 2025-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'In Lavorazione'), ('Shipped', 'Spedito'), ('Delivered', 'Consegnato'), ('Cancelled', 'Annullato')], default='Processing', max_length=50),
        ),
    ]
