# Generated by Django 5.2.3 on 2025-07-04 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_options_alter_address_phone_number_and_more'),
        ('orders', '0007_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_view_all_customers_orders', 'può vedere gli ordini di tutti i clienti'), ('can_change_order_status', 'può cambiare lo stato di un ordine')], 'verbose_name': 'Ordine', 'verbose_name_plural': 'Ordini'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data di acquisto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.address', verbose_name='Indirizzo di consegna'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Totale(€)'),
        ),
    ]
