# Generated by Django 5.2.3 on 2025-06-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(help_text="Slug unico per l'URL della categoria", max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Prodotto')),
                ('slug', models.SlugField(help_text="Slug unico per l'URL del prodotto", max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descrizione prodotto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('stock', models.IntegerField(default=0, help_text='Quantità di prodotti disponibili in magazzino.', verbose_name='Quantità Disponibile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ('name',),
            },
        ),
    ]
