# Generated by Django 5.2.3 on 2025-06-25 10:50

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_main', 'city'], 'permissions': [('can_select_address_in_checkout', 'Può selezionare indirizzo nel checkout')], 'verbose_name': 'Indirizzo', 'verbose_name_plural': 'Indirizzi'},
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Inserisci un numero di telefono italiano', regex='^\\d{1,15}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Inserire un CAP valido (5 cifre)', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_province',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Inserire la sigla delle provincia', regex='^[a-z]{2}$')]),
        ),
    ]
