# Generated by Django 5.2.3 on 2025-06-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_access_manager_dashboard', 'Può accedere alla dashboard degli store manager'), ('can_access_customer_dashboard', 'Può accedere alla dashboard clienti')]},
        ),
    ]
